{{- if and (.Values.enabled) (.Values.persistence.enabled) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: http-nas-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}