import React from 'react';
import styled, { withTheme } from 'styled-components';

import Helmet from 'react-helmet';

// import { red, green, blue } from "@material-ui/core/colors";

import {
  Divider as MuiDivider,
  Typography,
  Button as MuiButton,
  Box,
  CardContent,
  Card as MuiCard,
  Link,
} from '@material-ui/core';

import {
  Download as DownloadIcon,
} from 'react-feather';

import { spacing } from '@material-ui/system';
import RedacticsContext from '../../contexts/RedacticsContext';

const Card = styled(MuiCard)(spacing);

const Divider = styled(MuiDivider)(spacing);

const Button = styled(MuiButton)(spacing);

class CLI extends React.Component {
  static contextType = RedacticsContext;

  constructor(props: any) {
    super(props);

    this.download = this.download.bind(this);
  }

  download() {
    window.location.href = this.context.cliUrl;
  }

  /* eslint-disable max-len */

  render() {
    return (
      <React.Fragment>
        <Helmet title="Agent CLI" />

        <Typography variant="h1" gutterBottom display="inline">
          Agent CLI
        </Typography>

        <Divider my={6} />

        <Box mt={4}>
          <Typography variant="body1" gutterBottom>
            Information about the Redactics Agent CLI and sample database tables that can be installed for testing can be found below.
          </Typography>
        </Box>

        <Card mb={1} mt={8}>
          <CardContent>
            <Typography variant="h3" gutterBottom>
              Redactics Agent CLI
            </Typography>

            <Box mt={8}>
              <p>
                Click on the button below to download the Redactics Agent CLI. The Redactics CLI is a shell script that provides the following functionality:
              </p>
            </Box>

            <ul>
              <li>List and download of database exports generated by Redactics</li>
              <li>Manual triggering of Redactics jobs</li>
              <li>Sample table installation</li>
              <li>Output of job status</li>
              <li>Troubleshooting/diagnostics</li>
            </ul>

            <Box mt={4} mb={8}>
              <Button color="primary" onClick={this.download} variant="contained" size="large">
                <DownloadIcon />&nbsp;Download From Github (version {this.context.cliVersion})
              </Button>
              <Box mt={2}>
                The source code can be found within our <Link href="https://github.com/Redactics/redactics-osedition/tree/main/cli" target="_blank">Github repo</Link>.
              </Box>
            </Box>

            <Typography variant="h5" gutterBottom>
              Install Instructions
            </Typography>

            <ol>
              <li>Extract .zip file (this will extract a single shell script file)</li>
              <li>Assure that this shell script is executable (e.g. chmod +x /path/to/redactics.sh)</li>
              <li>(Optional) move to a directory of your choice accessible by your shell</li>
            </ol>

            <Typography variant="h5" gutterBottom>
              Usage
            </Typography>

            <p>
              Enter <code>/path/to/redactics.sh</code> to display usage instructions
            </p>

            <Typography variant="h5" gutterBottom>
              Requirements
            </Typography>

            <p>
              This script requires that you have the Kubernetes <Link target="_blank" rel="noreferrer" href="https://kubernetes.io/docs/tasks/tools/">kubectl</Link> tool available (authenticated to your cluster), and <Link target="_blank" rel="noreferrer" href="https://helm.sh/docs/intro/install">Helm</Link> both accessible by your shell.
            </p>

          </CardContent>
        </Card>
      </React.Fragment>
    );
  }
}

export default withTheme(CLI);
