{{- define "connections.script" }}
  #!/bin/sh -e
  # recreate connections
  {{- range .Values.airflow.connections }}
  echo "*** recreating connection ID {{ .id }}"
  airflow connections delete {{ .id }} || true
  airflow connections add "{{ .id }}"
  {{- if .type }} --conn-type {{ .type | quote }} {{ end -}}
  {{- if .uri }} --conn-uri {{ .uri | quote }} {{ end -}}
  {{- if .host }} --conn-host {{ .host | quote }} {{ end -}}
  {{- if .login }} --conn-login {{ .login | quote }} {{ end -}}
  {{- if .password }} --conn-password {{ .password | quote }} {{ end -}}
  {{- if .schema }} --conn-schema {{ .schema | quote }} {{ end -}}
  {{- if .port }} --conn-port {{ .port }} {{ end -}}
  {{- if .extra }} --conn-extra {{ .extra | quote }} {{ end -}}
  {{- end }}
{{- end }}
{{- if .Values.airflow.connections }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-connections
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  add-connections.sh: {{ include "connections.script" . | b64enc }}
{{- end }}
