# initial postgres container password init
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
type: Opaque
data:
  {{- range $key, $value := .Values.airflow.connections }}
    {{- if eq .id "redacticsDB" }}
    postgresql-password: {{ $value.password | b64enc | quote }}
    {{- end }}
  {{- end }}

# Airflow DB secret (https://airflow.apache.org/docs/helm-chart/stable/production-guide.html)
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-airflow-postgresql
type: Opaque
data:
  connection: {{ .Values.postgresql.connection | b64enc | quote }}
