import React from 'react';
import styled, { withTheme } from 'styled-components';
import { withStyles } from '@material-ui/core/styles';

import Helmet from 'react-helmet';

// import { red, green, blue } from "@material-ui/core/colors";

import {
  Divider as MuiDivider,
  Typography,
  Button as MuiButton,
  Box,
  CardContent,
  Card as MuiCard,
  Link,
  ExpansionPanel,
  ExpansionPanelDetails as MuiExpansionPanelDetails,
  ExpansionPanelSummary,
} from '@material-ui/core';

import {
  ExpandMore as ExpandMoreIcon,
} from '@material-ui/icons';

import {
  Download as DownloadIcon,
} from 'react-feather';

import { spacing } from '@material-ui/system';
import RedacticsContext from '../../contexts/RedacticsContext';

const Card = styled(MuiCard)(spacing);

const Divider = styled(MuiDivider)(spacing);

const ExpansionPanelDetails = withStyles({
  root: {
    display: 'block',
  },
})(MuiExpansionPanelDetails);

const Button = styled(MuiButton)(spacing);

class CLI extends React.Component {
  static contextType = RedacticsContext;

  constructor(props: any) {
    super(props);

    this.download = this.download.bind(this);
  }

  download() {
    window.location.href = this.context.cliUrl;
  }

  static expansionPanelChange(panel: string) {
    if (panel === 'developerDatasetDownload') {
      // save state that developer download info has been read
      localStorage.setItem('developerDatasetDownload', 'true');
    }
  }

  /* eslint-disable max-len */

  render() {
    return (
      <React.Fragment>
        <Helmet title="Developers" />

        <Typography variant="h1" gutterBottom display="inline">
          Developers
        </Typography>

        <Divider my={6} />

        <Box mt={4}>
          <Typography variant="body1" gutterBottom>
            Information about the Redactics SMART Agent CLI and sample database tables that can be installed for testing can be found below.
          </Typography>
        </Box>

        <Card mb={1} mt={8}>
          <CardContent>
            <Typography variant="h3" gutterBottom>
              Redactics SMART Agent CLI
            </Typography>

            <Box mt={8}>
              <p>
                Click on the button below to download the Redactics SMART Agent CLI. The Redactics CLI is a shell script that provides the following functionality:
              </p>
            </Box>

            <ul>
              <li>List and download of database exports generated by Redactics</li>
              <li>Manual triggering of Redactics jobs</li>
              <li>Redactics data repository management and dataset installation</li>
              <li>Initiation of PII scanning job (supports the <Link href="/usecases/piiscanner">Data Privacy: PII Scanner</Link> feature)</li>
              <li>Sample table installation</li>
              <li>Output of job status</li>
              <li>Troubleshooting/diagnostics</li>
            </ul>

            <Box mt={4} mb={8}>
              <Button color="primary" onClick={this.download} variant="contained" size="large">
                <DownloadIcon />&nbsp;Download From Github (version {this.context.cliVersion})
              </Button>
              <Box mt={2}>
                The source code can be found within our <Link href="https://github.com/Redactics/cli" target="_blank">Github repo</Link>.
              </Box>
            </Box>

            <Typography variant="h5" gutterBottom>
              Install Instructions
            </Typography>

            <ol>
              <li>Extract .zip file (this will extract a single shell script file)</li>
              <li>Assure that this shell script is executable (e.g. chmod +x /path/to/redactics.sh)</li>
              <li>(Optional) move to a directory of your choice accessible by your shell</li>
            </ol>

            <Typography variant="h5" gutterBottom>
              Usage
            </Typography>

            <p>
              Enter <code>/path/to/redactics.sh</code> to display usage instructions
            </p>

            <Typography variant="h5" gutterBottom>
              Requirements
            </Typography>

            <p>
              This script requires that you have the Kubernetes <Link target="_blank" rel="noreferrer" href="https://kubernetes.io/docs/tasks/tools/">kubectl</Link> tool available (authenticated to your cluster), and <Link target="_blank" rel="noreferrer" href="https://helm.sh/docs/intro/install">Helm</Link> both accessible by your shell.
            </p>

          </CardContent>
        </Card>

        <Box mt={8}>
          <Typography variant="h3" gutterBottom>
            Other Helpful Info/FAQs
          </Typography>
        </Box>

        <Box mt={4}>
          <ExpansionPanel>
            <ExpansionPanelSummary expandIcon={<ExpandMoreIcon />}>
              <Typography>Sample Table Installation Instructions</Typography>
            </ExpansionPanelSummary>
            <ExpansionPanelDetails>
              <Box>
                <p>
                  There are two sample tables that can be installed by the CLI, one containing a listing of olympic athletes that participated in the 2020 Tokyo olympics, and one containing sample demographic information for a marketing campaign - the schema for both is provided below. These tables can be installed with the following commands, where <code>[database ID]</code> is the ID of your database found at the top of your <Link href="/databases">database configurations</Link> and <code>[sample table]</code> is one of <code>olympics</code> or <code>marketing_campaign</code>. CSVs and full SQL schema for these datasets can also be found in our <Link href="https://github.com/Redactics/redactics-sampledatasets" target="_blank" rel="noreferrer">Github repo</Link>.
                </p>

                <Box mt={4}>
                  <code>redactics install-sample-table [database ID] [sample table]</code>
                </Box>

                <Box mt={8}>
                  <Typography variant="h5" gutterBottom>
                    Olympics Table Schema
                  </Typography>

                  <ul>
                    <li><b>id</b>: primary key (PostgreSQL numeric sequence)</li>
                    <li><b>name</b>: athlete name (varchar)</li>
                    <li><b>noc</b>: national olympic commitee (varchar)</li>
                    <li><b>discipline</b>: participation sport (varchar)</li>
                    <li><b>email</b>: a made up email address for this individual in the style of <code>firstnamelastname@olympics.com</code> (PII - varchar)</li>
                  </ul>
                </Box>

                <Box mt={8}>
                  <Typography variant="h5" gutterBottom>
                    Marketing Campaign Schema
                  </Typography>

                  <ul>
                    <li><b>id</b>: primary key (preset numeric int4 ID)</li>
                    <li><b>first_name</b>: (varchar)</li>
                    <li><b>last_name</b>: (varchar)</li>
                    <li><b>email</b>: a made up email address for this individual in the style of <code>firstnamelastname@gmail.com</code> (PII - varchar)</li>
                    <li><b>phone</b>: a made up phone number (PII - varchar)</li>
                    <li><b>last_login_ip</b>: a made up IP address (PII - varchar)</li>
                    <li><b>year_birth</b>: (int2)</li>
                    <li><b>education</b>: highest level of education obtained (varchar)</li>
                    <li><b>marital_status</b>: (varchar)</li>
                    <li><b>income</b>: (float4)</li>
                    <li><b>kidhome</b>: number of kids in the home (int2)</li>
                    <li><b>teenhome</b>: number of teenagers in the home (int2)</li>
                    <li><b>dt_customer</b>: date of customer&apos;s enrollment with the company (varchar)</li>
                    <li><b>recency</b>: number of days since customer&apos;s last purchase (int2)</li>
                    <li><b>mntwines</b>: amount spent on wine (float4)</li>
                    <li><b>mntfruits</b>: amount spent on fruit (float4)</li>
                    <li><b>mntmeatproducts</b>: amount spent on meat products (float4)</li>
                    <li><b>mntfishproducts</b>: amount spent on fish products (float4)</li>
                    <li><b>mntsweetproducts</b>: amount spent on sweet products (float4)</li>
                    <li><b>mntgoldprods</b>: amount spent on gold products (float4)</li>
                    <li><b>numdealspurchases</b>: number of purchases on limited time deals (int2)</li>
                    <li><b>numwebpurchases</b>: number of purchases made via the website (int2)</li>
                    <li><b>numcatalogpurchases</b>: number of purchases made via the store catalog (int2)</li>
                    <li><b>numstorepurchases</b>: number of visits to physical store locations (int2)</li>
                    <li><b>numwebvisitsmonth</b>: number of monthly visits to the website (int2)</li>
                    <li><b>acceptedcmp1</b>: campaign 1 website hits (int2)</li>
                    <li><b>acceptedcmp2</b>: campaign 2 website hits (int2)</li>
                    <li><b>acceptedcmp3</b>: campaign 3 website hits (int2)</li>
                    <li><b>acceptedcmp4</b>: campaign 4 website hits (int2)</li>
                    <li><b>acceptedcmp5</b>: campaign 5 website hits (int2)</li>
                    <li><b>complain</b>: number of complaints (int2)</li>
                    <li><b>z_costcontact</b>: cost to target individual (int2)</li>
                    <li><b>z_revenue</b>: revenue generated by individual (int2)</li>
                    <li><b>response</b>: total user responses (int2)</li>
                  </ul>
                </Box>
              </Box>
            </ExpansionPanelDetails>
          </ExpansionPanel>
        </Box>

        <Box mt={4}>
          <ExpansionPanel>
            <ExpansionPanelSummary expandIcon={<ExpandMoreIcon />}>
              <Typography>How to Create a Custom Data Feed</Typography>
            </ExpansionPanelSummary>
            <ExpansionPanelDetails>

              <Box>
                <p>
                  Data feeds allow you to perform some sort of work to your transformed/redacted datasets, for example sending them to the cloud for download by your employees, or passing off the dataset to some other platform or pipeline.
                </p>

                <p>
                  Here are some basic instructions for creating your own custom data feed container for use in your workflow (which you'll reference in your workflow configuration):
                </p>
              </Box>

              <Divider my={6} />

              <p>
                The fields in the configuration form align directly to Kubernetes fields. The only exception is automatically wrapping your command and arguments in shell invoked command, e.g. <code>/bin/bash -c &quot;&lt;your command&gt;&quot; &quot;&lt;your args&gt;&quot;</code>.  Redactics does this because the interface for fetching files created by Redactics is based on http streaming technology which supports Linux pipes so that your files can be transferred from Redactics directly to their ultimate destination without having to copy these files into your post export hook container first.
              </p>

              <Box mt={8}>
                <Typography variant="h4" gutterBottom>
                  HTTP Streaming Interface
                </Typography>

                <p>You can transfer files within your container in one of two ways:</p>

                <ol>
                  <li>Via the agent-file streamer script you can copy from our <Link href="https://github.com/Redactics/redactics-export-plugin-base/tree/master" target="_blank">Base Plugin Source Code</Link></li>
                  <li>Via direct curl commands</li>
                </ol>

                <Typography variant="h6" gutterBottom>
                  Agent-filestreamer Usage Examples:
                </Typography>

                <ul>
                  <li><code>agent-filestreamer list-files [database ID]</code>: lists files exported from <code>[database ID]</code></li>
                  <li><code>agent-filestreamer download-export [database ID] [filename]</code>: streams <code>[filename]</code> from <code>[database ID]</code> to stdout</li>
                  <li><code>agent-filestreamer download-export [database ID] complete-dump.sql | aws s3 cp - s3://your-bucket/complete-dump.sql</code>: streams <code>complete-dump.sql</code> to the provided AWS S3 bucket (assuming your container includes the AWS CLI and authentication to your bucket)</li>
                </ul>

                <Typography variant="h6" gutterBottom>
                  Direct Curl Command Examples:
                </Typography>

                <ul>
                  <li><code>curl -s http://redactics-http-nas:3000/file/[database ID]</code>: lists files exported from <code>[database ID]</code></li>
                  <li><code>curl -s --output - http://redactics-http-nas:3000/file/[database ID]%2F[filename]</code>: streams <code>[filename]</code> from <code>[database ID]</code> to stdout (note the &quot;%2F&quot; encoding here, used for traversing into a directory - the &quot;/&quot; character will not work here)</li>
                  <li><code>curl -s --output - http://redactics-http-nas:3000/file/[database ID]%2F[filename] | aws s3 cp - s3://your-bucket/complete-dump.sql</code>: streams <code>complete-dump.sql</code> to the provided AWS S3 bucket (assuming your container includes the AWS CLI and authentication to your bucket)</li>
                </ul>
              </Box>
            </ExpansionPanelDetails>
          </ExpansionPanel>
        </Box>

        <Box mt={4}>
          <ExpansionPanel>
            <ExpansionPanelSummary expandIcon={<ExpandMoreIcon />}>
              <Typography>How to Test the Redactics Agent Locally on your Laptop/PC</Typography>
            </ExpansionPanelSummary>
            <ExpansionPanelDetails>
              <p>
                The free <Link href="https://docs.docker.com/desktop/" target="_blank">Docker Desktop</Link> includes Kubernetes support built in. To enable Kubernetes, access your Docker preferences and find the <code>Enable Kubernetes</code> checkbox within the <code>Kubernetes</code> section.
              </p>

              <p>
                With Kubernetes enabled, as long as <code>Docker Desktop</code> is selected within your Docker menu -&gt; Kubernetes, you can install the Redactics agent locally. After installing Helm and running the Helm command provided in the <code>Agents</code> section, confirm that all Agent pods are healthy by running <code>kubectl get pods -n [your namespace]</code>, download the Redactics CLI if you haven&apos;t already done so (which supports using local Kubernetes clusters) to kick off jobs manually, and modify your Redactics configuration file provided in the Agent section to provide connection info to your database(s). This connection info is found right below the comment that says <code>this ID matches your workflow created within this web interface</code>.
              </p>

              <p>
                If you do not already have a database installed for testing purpose, you can piggyback upon the database provided by the Agent. Simply change:
              </p>
              <ul>
                <li>The <code>hostname</code> for this connection is <code>redacticsDB</code></li>
                <li>The <code>login</code> to match the "redacticsDB" connection in your Helm configuration file</li>
                <li>The <code>password</code> to match the "redacticsDB" connection in your Helm configuration file</li>
                <li>The <code>schema</code> to <code>redactics_tmp</code></li>
              </ul>

              <p>
                This database is installed to apply the data transformations on a copy of your source data, but you can use it to install your own sample tables including the sample tables installable via the Redactics CLI.
              </p>
            </ExpansionPanelDetails>
          </ExpansionPanel>
        </Box>

      </React.Fragment>
    );
  }
}

export default withTheme(CLI);
